name: Release Coraza WASM for Otoroshi

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag version to use for this release (e.g. 1.2.3)"
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.5"

      - name: Make script executable
        run: chmod +x ./build.sh

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run release script
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@users.noreply.github.com
          GOOS=: wasip1 
          GOARCH: wasm
        run: |
          ./build.sh "${{ inputs.version }}"
      - name: Release binary and SHA-256 checksum to GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: coraza-wasm-${{ inputs.version }}
          tag_name: ${{ inputs.version }}
          files: |
            ./coraza-${{ inputs.version }}-*.wasm
            ./coraza-${{ inputs.version }}-*.wasm.sha256
      - name: Read CRS latest tag
        id: read_crs_tag
        run: |
          echo "crs_tag=$(cat latest_crs_tag.txt)" >> "$GITHUB_OUTPUT"
      - name: Checkout MAIF/otoroshi
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@users.noreply.github.com
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://${{ secrets.OTOROSHI_PAT }}@github.com/MAIF/otoroshi.git --depth 1
          cd ./otoroshi
          git checkout -b chore/update-coraza-wasm-${{ github.event.inputs.version }}
          cp ../coraza-${{ inputs.version }}-crs-${{ steps.read_crs_tag.outputs.crs_tag }}.wasm ./otoroshi/conf/wasm/coraza.wasm
          git add --all
          git commit -am "chore(deps): update coraza.wasm to ${{ github.event.inputs.version }} (CRS ${{ steps.read_crs_tag.outputs.crs_tag }})"
          git push origin chore/update-coraza-wasm-${{ github.event.inputs.version }}
          curl -X POST https://api.github.com/repos/MAIF/otoroshi/pulls \
            -H "Authorization: Bearer ${{ secrets.OTOROSHI_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -d '{
              "title": "Update coraza.wasm to ${{ github.event.inputs.version }} (CRS ${{ steps.read_crs_tag.outputs.crs_tag }})",
              "head": "chore/update-coraza-wasm-${{ github.event.inputs.version }}",
              "base": "master",
              "body": "This PR updates `otoroshi/conf/wasm/coraza.wasm` to the version: ${{ github.event.inputs.version }} with CRS version: `${{ steps.read_crs_tag.outputs.crs_tag }}"
            }'
